### ISSUE TITLE
Operator should be able to install from different registries and tags

### ISSUE THREAD

**Issue by trshafer** [knative/serving-operator#1]
Currently knative serving release uses the registry: `gcr.io/knative-releases` and the build path: `github.com/knative/serving/cmd`. Additionally, the tag is built using a sha `sha256:1e40c99ff5977daa2d69873fff604c6d09651af1f9ff15aadf8849b3ee77ab45` instead of a tag number `0.6.0`. These fields should be customizable, so it could point to a registry of `quay.io/openshift-knative` or others.

I think it's reasonable to have reasonable defaults from knative serving, but support modifications by changing `KnativeServing` CR.

The configuration could look like:
```YAML
apiVersion: serving.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
spec:
  config:
  image:
    registry: "my-registry.io/my-knative-release/path"
    tag: "v0.6.0"
```

**Comment by trshafer** [comment]
Still unknown:

* Should each knative deployment have a separate "tag" (or revision) or should there only be one supported tag?
* Should this config live in the `KnativeServing` CR or should it live in a ConfigMap for the Operator?

**Comment by greghaynes** [comment]
For the multiple tag question theres two use cases I wonder about:

- Someone, possibly a platform provider, wants to cut a patch release of a specific component (e.g. fix a security bug in activator). In this case the whole cluster would need to be updated as all of the image tags would have to change. Even if the tags for other components point to the same sha I think the deployments themselves would need to perform a rollingupgrade as the deployment changed.
- When we support deploying from master its probably nice to support each image tag being unique (think: how ko generates image tag's).

What if instead this ConfigMap looks like follows:

```yaml
apiVersion: serving.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
spec:
  config:
    # If an image is not specified we generate it's URI using this
    default-image:
      registry: "my-registry.io/my-knative-release/path"
      tag: "v0.6.0"
    images:
      # Allow a user to override a specific image
      activator: <full image uri>
      ...
```

This would allow a user to set a single line in default-image for the 'I want to deploy the same tag for all images but using my registry' case, and also allow the patching a single component case as well as control for deploying from master with generated tags.
