### ISSUE TITLE
Support overriding cluster-local-gateway

### ISSUE THREAD

**Issue by trshafer** [knative/serving-operator#113]
This should be similar to the `knative-ingress-gateway` change

```yaml
spec:
  cluster-local-gateway:
    selector:
      istio: my-istio
```
