### ISSUE TITLE
Support for imagePullSecrets

### ISSUE THREAD

**Issue by trshafer** [knative/serving-operator#124]
knative by default does not ship with imagePullSecrets because the registry is put on gcr.io/knative-releases by default. However by supporting custom registries, the operator should also support imagePullSecrets.

https://kubernetes.io/docs/concepts/containers/images/#referring-to-an-imagepullsecrets-on-a-pod

Proposal:

```yaml
spec:
  registry:
    imagePullSecrets: "my-secrets"
    ...existing fields of "default" and "override"
```
