### ISSUE TITLE
KnativeServing options are not removed when KnativeServing CR changes

### ISSUE THREAD

**Issue by trshafer** [knative/serving-operator#138]
Applying a KnativeServing with say a spec of

```yaml
apiVersion: serving.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
spec:
  config:
    logging:
      loglevel.controller: "debug"
```

And then applying the spec of:

```yaml
apiVersion: serving.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
```

The config is not reverted. This is the same for the other config options.

I believe it is because the way the mutations happen is that they mutate the original manifest: https://github.com/knative/serving-operator/tree/e0413caae7af488613c242dda73dfd93ee4a2b97/pkg/reconciler/knativeserving/common. They need to not mutate the original manifest and instead return a new manifest.
