### ISSUE TITLE
Operator should validate cluster before installing knative serving

### ISSUE THREAD

**Issue by trshafer** [knative/serving-operator#2]
If the cluster is not setup to support the intended version of knative it should report an error status.

When the user applies the `KnativeServing` CR,
```YAML
apiVersion: serving.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
```

the operator should validate that the k8s version is supported and the dependencies are available.

Possible validations:
* k8s version
* ingress
  * istio, gloo, ambassador
* cert-manager

If these requirements are not met, the operator should report this in the `status` field. That status could include `healthy` and `errors` fields similar to https://youtu.be/LPejvfBR5_w?t=480.
