### ISSUE TITLE
Add support for controller custom certificate in KnativeServing CRD

### ISSUE THREAD

**Issue by jcrossley3** [knative/serving-operator#210]
To enable the controller to trust self-signed certs from a registry, I'd like to propose the following addition to the `KnativeServing` CR:

```yaml
spec:
  controller-custom-certs:
    name: config-service-ca
    type: ConfigMap
```
The operator would then configure the controller's deployment per [these instructions](https://knative.dev/docs/serving/tag-resolution/). The other supported type would be `Secret`, both of which the user would be expected to create.
