### ISSUE TITLE
The serving-operator should export prometheus metrics

### ISSUE THREAD

**Issue by trshafer** [knative/serving-operator#5]
This will require a creating a `Service` that exposes a metrics port similar to the knative serving controller (https://github.com/knative/serving/blob/9bcd6f482377c5c42665e7d5fad9072a180301fc/config/400-controller-service.yaml#L25)

Example service:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: serving-operator
    serving.knative.dev/release: devel
  name: serving-operator
  namespace: default
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: serving-operator
```
