### ISSUE TITLE
KnativeServing CR should be able to override istio selector

### ISSUE THREAD

**Issue by trshafer** [knative/serving-operator#50]
Currently the knative-ingress-gateway is hardcoded to `ingressgateway`: https://github.com/knative/serving/blob/619115aa63ea29272c8c4f13d37a3eb2317e4cba/config/202-gateway.yaml#L12. 

This should be configurable in the `KnativeServing CRD`.

Proposal
```yaml
spec:
  knative-ingress-gateway: 
    spec:
      selector:
        istio: "my-ingress" 
      ...options to override all knative-ingress-gateway spec.
```

Is it important for this proposal to encompass the ability to select which ingress to use?
