### ISSUE TITLE
operator should ensure all serving components are remain installed as long as CR is present

### ISSUE THREAD

**Issue by yu2003w** [knative/serving-operator#81]
/kind feature

**Branch:** 
/master
/HEAD

**Current Behavior:**
Currently after installing Knative-serving with serving-operator, all components such as controller, activator, autoscaler and so on are deployed but not become 'available' due to some other reasons.
For example, image pull secret is missing.
Then delete the deployments in namespace knative-serving, operator will not reinstall the deployments again.

**Expected Behavior:**
operator could reinstall deployments as long as CR still present.

 **Detailed Procedure**
1, remove image pull secret from namespace knative-serving
2, update serving_v1alpha1_knativeserving_cr.yaml to apply customized images
```
spec:
  registry:
    override:
      activator: icpdev.icp:8500/imgrepo/serving-activator-amd64:v0.6.1
      autoscaler: icpdev.icp:8500/imgrepo/serving-autoscaler-amd64:v0.6.1
      controller: icpdev.icp:8500/imgrepo/serving-controller-amd64:v0.6.1
      networking-certmanager: icpdev.icp:8500/imgrepo/serving-certmanager-amd64:v0.6.1
      networking-istio: icpdev.icp:8500/imgrepo/serving-istio-amd64:v0.6.1
      webhook: icpdev.icp:8500/imgrepo/serving-webhook-amd64:v0.6.1
```
2, launch serving-operator to install knative-serving
3, delete deployments in namespace knative-serving.
deleted deployments are not created again.
