### ISSUE TITLE
Disable installation of certain deployments

### ISSUE THREAD

**Issue by trshafer** [knative/serving-operator#82]
Some installations do not want the certain deployments, such as networking-certmanager or networking-istio. 

This can be accomplished by adding additional configuration to the `KnativeServing` CRD.

## Proposal 1
Proposal 1 supports only skipping deployments. This would be look for the `networking-istio` name field of the deployment.

```yaml
spec:
  deployments:
    networking-istio: false
```

## Proposal 2

Another proposal is to add the ability to skip any resource:

```yaml
spec:
  skip:
    - resource: apps/v1/Deployment 
      name: networking-istio
```
