### ISSUE TITLE
Operator merges KnativeServing resource with the one in config/crds.

### ISSUE THREAD

**Issue by trshafer** [knative/serving-operator#93]
If the user applies a `KnativeServing` before applying the operator, the operator will smart merge the currently applied CR with https://github.com/knative/serving-operator/blob/master/config/crds/serving_v1alpha1_knativeserving_cr.yaml.

Steps to reproduce:
```
kubectl apply -f config/crds/serving_v1alpha1_knativeserving_crd.yaml
```
Apply a custom CR. For example:
```yaml
apiVersion: serving.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    istio:
      gateway.knative-ingress-gateway: "my-istio.my-istio-system.svc.cluster.local"
```

Then apply the operator:
```yaml
ko apply -f config/
```

The `KnativeServing` will also include the spec from the config directory:

```yaml
kubectl get knativeserving -o yaml --all-namespaces
```
